return Exception(CAUSE_MACHINE_ECALL, Zeros(32));
